version: 1.0.{build}
image:
  - Visual Studio 2019

platform:
  - x64

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node stable x64
  - yarn install

build_script:
  - npx envinfo
  - yarn run electron-build

test: off
